mutation addCardMutation($boardSlug: String!, $kind: String!, $body: String!) {
  addCard(
    input: { attributes: { boardSlug: $boardSlug, kind: $kind, body: $body } }
  ) {
    card {
      id
    }
    errors {
      fullMessages
    }
  }
}
