#import '../../fragments/action_item.graphql'
subscription actionItemAddedSubscription($boardSlug: String!) {
  actionItemAdded(boardSlug: $boardSlug) {
   ...ActionItem
  }
}

subscription actionItemMovedSubscription($boardSlug: String!) {
  actionItemMoved(boardSlug: $boardSlug) {
   ...ActionItem
  }
}

subscription actionItemDestroyedSubscription($boardSlug: String!) {
  actionItemDestroyed(boardSlug: $boardSlug) {
   id
  }
}

subscription actionItemUpdatedSubscription($boardSlug: String!) {
  actionItemUpdated(boardSlug: $boardSlug) {
   ...ActionItem
  }
}
