#import '../../fragments/card.graphql'

subscription cardAddedSubscription($boardSlug: String!) {
  cardAdded(boardSlug: $boardSlug) {
   ...Card
  }
}

subscription cardDestroyedSubscription($boardSlug: String!) {
  cardDestroyed(boardSlug: $boardSlug) {
    id
    kind
  }
}

subscription cardUpdatedSubscription($boardSlug: String!) {
  cardUpdated(boardSlug: $boardSlug) {
   ...Card
  }
}
